## NBA Playoff Performers Project Part 1 - Data Scraping

### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import requests
import time
import json

In [3]:
from bs4 import BeautifulSoup

In [4]:
years = list(range(2019,2024))

### Scraping from Basketball Reference

In [4]:
regular_url = 'https://www.basketball-reference.com/leagues/NBA_{}_advanced.html'

In [5]:
playoff_url = 'https://www.basketball-reference.com/playoffs/NBA_{}_advanced.html'

In [13]:
for year in years:
    url = regular_url.format(year)
    data = requests.get(url)
    
    with open("C:/Users/kevin/Documents/regular season stats/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)

In [14]:
for year in years:
    url = playoff_url.format(year)
    data = requests.get(url)
    
    with open("C:/Users/kevin/Documents/playoff stats/{}.html".format(year), "w+", encoding='utf-8') as f:
        f.write(data.text)

Testing with just 2019 to see how the data looks.

In [16]:
with open("C:/Users/kevin/Documents/regular season stats/2019.html", encoding='utf-8') as f:
    page = f.read()

In [17]:
soup = BeautifulSoup(page, "html.parser")

In [19]:
regularstats2019 = soup.find(id="advanced_stats")

In [22]:
regular_2019 = pd.read_html(str(regularstats2019))[0]

In [23]:
regular_2019

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,1,Álex Abrines,SG,25,OKC,31,588,6.3,.507,.809,...,NaN,0.1,0.6,0.6,.053,NaN,-3.7,0.4,-3.3,-0.2
1,2,Quincy Acy,PF,28,PHO,10,123,2.9,.379,.833,...,NaN,-0.1,0.0,-0.1,-0.022,NaN,-7.6,-0.5,-8.1,-0.2
2,3,Jaylen Adams,PG,22,ATL,34,428,7.6,.474,.673,...,NaN,-0.1,0.2,0.1,.011,NaN,-3.8,-0.5,-4.3,-0.2
3,4,Steven Adams,C,25,OKC,80,2669,18.5,.591,.002,...,NaN,5.1,4.0,9.1,.163,NaN,0.7,0.4,1.1,2.1
4,5,Bam Adebayo,C,21,MIA,82,1913,17.9,.623,.031,...,NaN,3.4,3.4,6.8,.171,NaN,-0.4,2.2,1.8,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,82,19.4,.640,.000,...,NaN,0.2,0.1,0.3,.191,NaN,-2.3,-1.9,-4.3,0.0
730,529,Ante Žižić,C,22,CLE,59,1082,16.2,.590,.000,...,NaN,1.7,0.3,2.0,.087,NaN,-1.1,-2.1,-3.2,-0.3
731,530,Ivica Zubac,C,21,TOT,59,1040,18.9,.604,.000,...,NaN,1.9,1.3,3.2,.148,NaN,-0.2,-0.2,-0.5,0.4
732,530,Ivica Zubac,C,21,LAL,33,516,19.5,.633,.000,...,NaN,1.1,0.6,1.8,.165,NaN,-0.3,0.1,-0.2,0.2
733,530,Ivica Zubac,C,21,LAC,26,524,18.3,.574,.000,...,NaN,0.7,0.7,1.4,.132,NaN,-0.2,-0.5,-0.7,0.2

I then create functions to pull regular season and playoff data for the years 2019-2023.

In [34]:
dfs = []
for year in years:
    with open("C:/Users/kevin/Documents/regular season stats/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    regularstats = soup.find(id="advanced_stats")
    regular = pd.read_html(str(regularstats))[0]
    regular["Year"] = year
    
    dfs.append(regular)

In [35]:
dfs2 = []
for year in years:
    with open("C:/Users/kevin/Documents/playoff stats/{}.html".format(year), encoding='utf-8') as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    playoffstats = soup.find(id="advanced_stats")
    playoff = pd.read_html(str(playoffstats))[0]
    playoff["Year"] = year
    
    dfs2.append(playoff)

In [36]:
dfs2[0].columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'Unnamed: 19', 'OWS', 'DWS', 'WS', 'WS/48', 'Unnamed: 24', 'OBPM',
       'DBPM', 'BPM', 'VORP', 'Year'],
      dtype='object')

In [37]:
regs = pd.concat(dfs)

In [38]:
playoffs = pd.concat(dfs2)

In [40]:
playoffs

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP,Year
0,1,Steven Adams,C,25,OKC,5,159,15.7,.648,.024,...,0.2,0.1,0.3,.103,NaN,-0.1,1.9,1.8,0.2,2019
1,2,LaMarcus Aldridge,C,33,SAS,7,244,21.8,.517,.091,...,0.5,0.2,0.7,.130,NaN,2.5,-0.2,2.3,0.3,2019
2,3,Grayson Allen,SG,23,UTA,2,14,10.5,.446,.429,...,0.0,0.0,0.0,.003,NaN,-1.6,-3.5,-5.1,0.0,2019
3,4,Jarrett Allen,C,20,BRK,5,110,22.5,.674,.000,...,0.4,0.0,0.4,.182,NaN,2.0,1.4,3.4,0.2,2019
4,5,Al-Farouq Aminu,PF,28,POR,16,399,11.0,.473,.468,...,0.1,0.3,0.4,.052,NaN,-0.8,-0.1,-0.9,0.1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,213,Ziaire Williams,SF,21,MEM,4,12,-2.4,.357,.429,...,-0.1,0.0,-0.1,-0.275,NaN,-6.3,-1.9,-8.2,0.0,2023
223,214,Trae Young,PG,24,ATL,6,230,21.1,.521,.362,...,0.3,0.0,0.3,.066,NaN,4.7,-1.1,3.6,0.3,2023
224,215,Omer Yurtseven,C,24,MIA,8,16,5.5,.286,.286,...,-0.1,0.0,0.0,-0.113,NaN,-8.6,-4.5,-13.1,0.0,2023
225,216,Cody Zeller,C,30,MIA,21,174,7.5,.553,.000,...,-0.1,0.2,0.1,.024,NaN,-6.7,-0.1,-6.8,-0.2,2023
226,217,Ivica Zubac,C,25,LAC,5,130,14.1,.621,.000,...,0.1,0.0,0.1,.041,NaN,-1.2,-1.0,-2.3,0.0,2023

In [41]:
playoffs[playoffs['Player'] == 'Andre Drummond']

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP,Year
47,46,Andre Drummond,C,25,DET,4,127,15.6,.451,.019,...,-0.2,0.1,-0.1,-0.042,NaN,-1.9,-1.0,-2.9,0.0,2019
64,62,Andre Drummond,C,27,LAL,5,105,19.2,.618,.000,...,0.0,0.2,0.2,.112,NaN,-0.5,0.7,0.2,0.1,2021
68,66,Andre Drummond,C,28,BRK,4,60,10.0,.568,.000,...,-0.1,0.1,0.0,-0.012,NaN,-4.9,1.7,-3.2,0.0,2022

In [3]:
regs = regs.drop(['Unnamed: 19','Unnamed: 24'], axis=1)
playoffs = playoffs.drop(['Unnamed: 19','Unnamed: 24'], axis=1)

In [8]:
regs.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'Year'],
      dtype='object')

### Data Cleaning

Checked null values and found there aren't many and the players that do have null values are not very relevant.

In [14]:
regs.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
MP         0
PER        0
TS%       26
3PAr      28
FTr       28
ORB%       0
DRB%       0
TRB%       0
AST%       0
STL%       0
BLK%       0
TOV%      23
USG%       0
OWS        0
DWS        0
WS         0
WS/48      0
OBPM       0
DBPM       0
BPM        0
VORP       0
Year       0
dtype: int64

In [15]:
print(regs[regs.isnull().any(axis=1)])
#the players with null values aren't worth keeping

       Rk               Player Pos Age   Tm  G MP    PER   TS% 3PAr  ...  \
316   233         John Holland  SF  30  CLE  1  1    0.0   NaN  NaN  ...
384   282          George King  SF  25  PHO  1  6    1.9   NaN  NaN  ...
495   359        Eric Moreland  PF  27  PHO  1  5    3.9   NaN  NaN  ...
625   451         Kobi Simmons  PG  21  CLE  1  2    0.0   NaN  NaN  ...
640   460         Ray Spalding  PF  21  DAL  1  1    0.0   NaN  NaN  ...
679   488           Tyler Ulis  PG  23  CHI  1  1    0.0   NaN  NaN  ...
801    52       Marques Bolden   C  21  CLE  1  3   19.8   NaN  NaN  ...
1135  307          J.P. Macura  SG  24  CLE  1  1    0.0   NaN  NaN  ...
1541  100           Gary Clark  SF  26  DEN  2  4    2.9   NaN  NaN  ...
1670  195        Ashton Hagans  PG  21  MIN  2  4  -12.4   NaN  NaN  ...
2194   43          Jordan Bell   C  27  CHI  1  2   29.9   NaN  NaN  ...
2269   98  Willie Cauley-Stein   C  28  PHI  2  6    4.2   NaN  NaN  ...
2313  132           Sam Dekker  PF  27  TOR  1  1    0.0   NaN  NaN  ...
2314  133      Javin DeLaurier   C  23  MIL  1  3   15.6   NaN  NaN  ...
2348  155      Jaime Echenique   C  24  WAS  1  3    0.0   NaN  NaN  ...
2388  180       Wenyen Gabriel  PF  24  BRK  1  1   11.8   NaN  NaN  ...
2431  215           Tyler Hall  SG  24  NYK  1  2    0.0   NaN  NaN  ...
2524  275        DeJon Jarreau  SG  24  IND  1  1    0.0   NaN  NaN  ...
2609  331        Scottie Lewis  SG  21  CHO  2  7   14.6  .568  NaN  ...
2668  378           C.J. Miles  SG  34  BOS  1  2   -7.8   NaN  NaN  ...
2690  391         Juwan Morgan  PF  24  BOS  1  4    0.0   NaN  NaN  ...
2699  398           Ade Murkey  SG  24  SAC  1  1    0.0   NaN  NaN  ...
2819  490     Tomáš Satoranský  SF  30  SAS  1  9   12.8  .852  NaN  ...
2836  502          Chris Silva  PF  25  MIN  1  3    3.8   NaN  NaN  ...
2973  599         Moses Wright  PF  23  LAC  1  1   31.2   NaN  NaN  ...
3076   66          Moses Brown   C  23  BRK  2  6   -2.6   NaN  NaN  ...
3187  151   Michael Foster Jr.  PF  20  PHI  1  1    0.0   NaN  NaN  ...
3661  515     Alondes Williams  SG  23  BRK  1  5  -20.9   NaN  NaN  ...

      USG%   OWS  DWS    WS   WS/48   OBPM  DBPM    BPM VORP  Year
316    0.0   0.0  0.0   0.0  -0.032   -3.4  -1.6   -5.0  0.0  2019
384    0.0   0.0  0.0   0.0  -0.001   -5.8  -2.1   -7.9  0.0  2019
495    0.0   0.0  0.0   0.0    .077   -6.3   0.2   -6.1  0.0  2019
625    0.0   0.0  0.0   0.0  -0.033   -7.4  -3.2  -10.6  0.0  2019
640    0.0   0.0  0.0   0.0    .000   -7.5  -5.0  -12.6  0.0  2019
679    0.0   0.0  0.0   0.0  -0.015   -7.7  -2.7  -10.4  0.0  2019
801    0.0   0.0  0.0   0.0    .282   -5.8  11.3    5.4  0.0  2020
1135   0.0   0.0  0.0   0.0  -0.022   -5.2  -1.2   -6.4  0.0  2020
1541   0.0   0.0  0.0   0.0    .037   -4.4  -2.0   -6.5  0.0  2021
1670  10.5   0.0  0.0   0.0  -0.353  -13.7  -7.4  -21.1  0.0  2021
2194   0.0   0.0  0.0   0.0    .600   -8.1  10.8    2.7  0.0  2022
2269   0.0   0.0  0.0   0.0    .136   -4.6   5.8    1.2  0.0  2022
2313   0.0   0.0  0.0   0.0    .003   -6.2  -3.4   -9.6  0.0  2022
2314   0.0   0.0  0.0   0.0    .260   -4.8  11.8    7.0  0.0  2022
2348   0.0   0.0  0.0   0.0  -0.012   -5.5  -3.0   -8.5  0.0  2022
2388   0.0   0.0  0.0   0.0    .167   -1.9   0.3   -1.6  0.0  2022
2431   0.0   0.0  0.0   0.0    .007   -8.1  -0.5   -8.5  0.0  2022
2524   0.0   0.0  0.0   0.0  -0.022   -6.5  -1.5   -8.0  0.0  2022
2609   5.3   0.0  0.0   0.0    .164    0.0   5.9    6.0  0.0  2022
2668   0.0   0.0  0.0   0.0    .030  -16.3   0.0  -16.3  0.0  2022
2690   0.0   0.0  0.0   0.0    .024   -4.0  -2.0   -6.0  0.0  2022
2699   0.0   0.0  0.0   0.0  -0.017   -7.4  -2.3   -9.7  0.0  2022
2819   8.3   0.0  0.0   0.0    .200    0.8  -2.1   -1.3  0.0  2022
2836   0.0   0.0  0.0   0.0    .052   -5.3  -0.5   -5.8  0.0  2022
2973   0.0   0.0  0.0   0.0    .443   10.8  13.4   24.2  0.0  2022
3076   7.4   0.0  0.0   0.0  -0.129  -12.7   2.8   -9.9  0.0  2023
3187   0.0   0.0  0.0   0.0    .010   -7.2  -1.9   -9.2  0.0  2023
3661  17.7  -0.1  0.0  -0.1  -0.517  -21.3  -5.2  -26.5  0.0  2023

[28 rows x 28 columns]

In [4]:
regs = regs.dropna()

In [18]:
playoffs.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
MP         0
PER        6
TS%       41
3PAr      45
FTr       45
ORB%       6
DRB%       6
TRB%       6
AST%       6
STL%       6
BLK%       6
TOV%      35
USG%       6
OWS        0
DWS        0
WS         0
WS/48      6
OBPM       0
DBPM       0
BPM        0
VORP       0
Year       0
dtype: int64

In [21]:
print(playoffs[playoffs.isnull().any(axis=1)])
#these guys are ok to remove as well

       Rk                  Player Pos Age   Tm  G  MP    PER    TS% 3PAr  ...  \
27     27           José Calderón  PG  37  DET  3  10   21.4    NaN  NaN  ...
32     32              Gary Clark  PF  24  HOU  2   4    3.0    NaN  NaN  ...
163   157            Kyle O'Quinn   C  28  IND  1   2  -27.5    NaN  NaN  ...
194   186            Zhaire Smith  SG  19  PHI  2   5   10.5    NaN  NaN  ...
196   188           Edmond Sumner  PG  23  IND  1   2   12.5    NaN  NaN  ...
207   199       Jarred Vanderbilt  PF  19  DEN  3   5   11.3    NaN  NaN  ...
247    25           Deonte Burton  SF  26  OKC  1   2    0.0    NaN  NaN  ...
253    31          Tyson Chandler   C  37  HOU  1   0    NaN   .000  NaN  ...
264    41              Tyler Cook  SF  22  DEN  1   4    5.8    NaN  NaN  ...
279    56          Carsen Edwards  SG  21  BOS  1   3    3.8    NaN  NaN  ...
332   106           Alize Johnson  PF  23  IND  1   0    NaN    NaN  NaN  ...
358   131         Frank Mason III  PG  25  MIL  2   2   16.4    NaN  NaN  ...
383   155             Joakim Noah   C  34  LAC  2   2    0.0    NaN  NaN  ...
388   160            Kyle O'Quinn   C  29  PHI  1   6  -19.7    NaN  NaN  ...
396   167            Norvel Pelle   C  26  PHI  1   7   14.3    NaN  NaN  ...
398   169         Vincent Poirier   C  26  BOS  1   2   44.6    NaN  NaN  ...
430   200            Gabe Vincent  PG  23  MIA  1   0    NaN    NaN  NaN  ...
446   215     Nigel Williams-Goss  PG  25  UTA  1   2   17.9    NaN  NaN  ...
459    11          Udoka Azubuike   C  21  UTA  1   1   12.0    NaN  NaN  ...
514    63            Jared Dudley  PF  35  LAL  2   5    0.0    NaN  NaN  ...
520    69              Tacko Fall   C  25  BOS  1   1   11.9    NaN  NaN  ...
543    91              Josh Green  SG  20  DAL  1   4    0.0    NaN  NaN  ...
586   132              Kevin Knox  SF  21  NYK  1   4   43.4  1.136  NaN  ...
621   165            Juwan Morgan  PF  23  UTA  2   6   11.4    NaN  NaN  ...
666   208              Jay Scrubb  SG  20  LAC  6   8    1.6    NaN  NaN  ...
682   223        Anthony Tolliver  PF  35  PHI  1   2   -7.3    NaN  NaN  ...
686   227           Rayjon Tucker  PG  23  PHI  1   2    3.5   .568  NaN  ...
695   236         Justise Winslow  SF  24  MEM  1   3   14.0    NaN  NaN  ...
724    25             Isaac Bonga  SF  22  TOR  1   3   30.3  1.136  NaN  ...
770    69         Kessler Edwards  SF  21  BRK  2   7   -2.2    NaN  NaN  ...
844   140            Paul Millsap   C  36  PHI  1   6    5.0    NaN  NaN  ...
864   159             Josh Okogie  SG  23  MIN  1   2    0.0    NaN  NaN  ...
885   179          Day'Ron Sharpe  PF  20  BRK  1   0    NaN    NaN  NaN  ...
893   186          Garrett Temple  SG  35  NOP  1   2    6.2    NaN  NaN  ...
895   188              Cam Thomas  SG  20  BRK  1   0    NaN    NaN  NaN  ...
933     8  Thanasis Antetokounmpo  PF  30  MIL  2   5    0.0    NaN  NaN  ...
948    22      Brandon Boston Jr.  SF  21  LAC  1   1  -50.5    NaN  NaN  ...
957    31           Thomas Bryant   C  25  DEN  1   0    NaN    NaN  NaN  ...
966    40             Amir Coffey  SF  25  LAC  1   1    0.0    NaN  NaN  ...
986    59         Kessler Edwards  SF  22  SAC  6   7    1.7    NaN  NaN  ...
1015   86           Aaron Holiday  PG  26  ATL  1   4   -4.9    NaN  NaN  ...
1026   97         DaQuan Jeffries  SG  25  NYK  2   5   -6.7    NaN  NaN  ...
1074  142       Wendell Moore Jr.  SG  21  MIN  1   2  -26.6    NaN  NaN  ...
1100  167           Jason Preston  PG  23  LAC  1   1    0.0    NaN  NaN  ...
1125  191           Edmond Sumner  SG  27  BRK  1   4    8.4    NaN  NaN  ...

      USG%   OWS  DWS    WS   WS/48   OBPM   DBPM    BPM VORP  Year
27     0.0   0.0  0.0   0.0    .183    5.0    5.8   10.8  0.0  2019
32     0.0   0.0  0.0   0.0    .048   -1.6    1.0   -0.6  0.0  2019
163   23.0   0.0  0.0   0.0  -0.688  -35.8   -3.7  -39.6  0.0  2019
194    0.0   0.0  0.0   0.0    .136   -3.6    7.7    4.1  0.0  2019
196    0.0   0.0  0.0   0.0    .175   -9.9   12.1    2.1  0.0  2019
207    0.0   0.0  0.0   0.0    .086   -1.3    4.8    3.5  0.0  2019
247    0.0   0.0  0.0   0.0    .020   -3.5   -1.4   -4.9  0.0  2020
253    NaN   0.0  0.0   0.0     NaN    0.0    0.0    0.0  0.0  2020
264    0.0   0.0  0.0   0.0    .059   -5.0   -0.2   -5.2  0.0  2020
279    0.0   0.0  0.0   0.0    .079   -2.9    3.0    0.1  0.0  2020
332    NaN   0.0  0.0   0.0     NaN   -4.2   -2.9   -7.1  0.0  2020
358    0.0   0.0  0.0   0.0    .237    4.4    0.0    4.4  0.0  2020
383    0.0   0.0  0.0   0.0    .004   -3.2   -2.6   -5.8  0.0  2020
388   14.5  -0.1  0.0  -0.1  -0.419  -27.0    0.9  -26.1  0.0  2020
396    0.0   0.0  0.0   0.0    .111   -0.6    6.6    6.0  0.0  2020
398    0.0   0.0  0.0   0.0    .564   17.4   33.0   50.4  0.0  2020
430    NaN   0.0  0.0   0.0     NaN   -4.7    0.7   -4.0  0.0  2020
446    0.0   0.0  0.0   0.0    .233    4.8    1.0    5.8  0.0  2020
459    0.0   0.0  0.0   0.0    .116    2.2    1.8    3.9  0.0  2021
514    0.0   0.0  0.0   0.0    .022   -5.2    0.0   -5.2  0.0  2021
520    0.0   0.0  0.0   0.0    .092    1.2   -0.5    0.7  0.0  2021
543    0.0   0.0  0.0   0.0  -0.029   -6.2   -0.5   -6.8  0.0  2021
586    9.8   0.0  0.0   0.1    .627   19.3   17.1   36.4  0.0  2021
621    0.0   0.0  0.0   0.0    .178    1.0    1.7    2.7  0.0  2021
666    0.0   0.0  0.0   0.0    .013   -4.6   -0.4   -5.0  0.0  2021
682    0.0   0.0  0.0   0.0    .037  -16.7    0.8  -15.9  0.0  2021
686   18.9   0.0  0.0   0.0    .125  -14.1   -2.3  -16.4  0.0  2021
695    0.0   0.0  0.0   0.0    .126    3.6    7.3   10.9  0.0  2021
724   13.6   0.0  0.0   0.0    .551   -0.2    4.4    4.3  0.0  2022
770    6.6   0.0  0.0   0.0  -0.104  -10.8    6.4   -4.4  0.0  2022
844    0.0   0.0  0.0   0.0    .111   -3.3    4.4    1.1  0.0  2022
864    0.0   0.0  0.0   0.0  -0.010   -2.6   -2.3   -4.8  0.0  2022
885    NaN   0.0  0.0   0.0     NaN   -1.8   -3.9   -5.7  0.0  2022
893    0.0   0.0  0.0   0.0    .024   -4.7    2.5   -2.2  0.0  2022
895    NaN   0.0  0.0   0.0     NaN   -2.0   -3.4   -5.4  0.0  2022
933    0.0   0.0  0.0   0.0  -0.017   -5.2   -2.3   -7.5  0.0  2023
948   42.0   0.0  0.0   0.0  -1.438  -40.9  -17.3  -58.2  0.0  2023
957    NaN   0.0  0.0   0.0     NaN   -3.7   -0.7   -4.3  0.0  2023
966    0.0   0.0  0.0   0.0  -0.048   -3.7   -1.8   -5.5  0.0  2023
986    0.0   0.0  0.0   0.0    .026   -5.8   -0.3   -6.2  0.0  2023
1015  10.3   0.0  0.0   0.0  -0.273   -8.4   -3.3  -11.6  0.0  2023
1026   0.0   0.0  0.0   0.0    .030  -19.0   -1.0  -20.1  0.0  2023
1074  23.1   0.0  0.0   0.0  -0.757  -24.9   -9.0  -33.9  0.0  2023
1100   0.0   0.0  0.0   0.0  -0.048   -4.9   -2.8   -7.6  0.0  2023
1125   0.0   0.0  0.0   0.0    .100    1.3   -1.1    0.2  0.0  2023

[45 rows x 28 columns]

In [5]:
playoffs = playoffs.dropna()

In [23]:
regs.head(20)
#some guys have multiple rows when they played for multiple teams in a year; ex. Ryan Anderson

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,1,Álex Abrines,SG,25,OKC,31,588,6.3,.507,.809,...,12.2,0.1,0.6,0.6,.053,-3.7,0.4,-3.3,-0.2,2019
1,2,Quincy Acy,PF,28,PHO,10,123,2.9,.379,.833,...,9.2,-0.1,0.0,-0.1,-0.022,-7.6,-0.5,-8.1,-0.2,2019
2,3,Jaylen Adams,PG,22,ATL,34,428,7.6,.474,.673,...,13.5,-0.1,0.2,0.1,.011,-3.8,-0.5,-4.3,-0.2,2019
3,4,Steven Adams,C,25,OKC,80,2669,18.5,.591,.002,...,16.4,5.1,4.0,9.1,.163,0.7,0.4,1.1,2.1,2019
4,5,Bam Adebayo,C,21,MIA,82,1913,17.9,.623,.031,...,15.8,3.4,3.4,6.8,.171,-0.4,2.2,1.8,1.8,2019
5,6,Deng Adel,SF,21,CLE,19,194,2.7,.424,.639,...,9.9,-0.2,0.0,-0.2,-0.054,-5.9,-1.6,-7.5,-0.3,2019
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,22,8.2,.322,.400,...,25.0,-0.1,0.0,0.0,-0.051,-7.9,2.1,-5.8,0.0,2019
7,8,LaMarcus Aldridge,C,33,SAS,81,2687,22.9,.576,.032,...,26.9,6.4,2.9,9.3,.167,2.4,-0.6,1.8,2.6,2019
8,9,Rawle Alkins,SG,21,CHI,10,120,8.1,.418,.308,...,19.0,-0.1,0.0,-0.1,-0.042,-3.8,-3.5,-7.3,-0.2,2019
9,10,Grayson Allen,SG,23,UTA,38,416,7.5,.516,.556,...,24.4,-0.4,0.4,0.0,.002,-4.2,-2.1,-6.3,-0.5,2019
10,11,Jarrett Allen,C,20,BRK,80,2096,18.5,.632,.079,...,15.9,4.4,3.3,7.6,.175,0.2,1.4,1.6,1.9,2019
11,12,Kadeem Allen,PG,26,NYK,19,416,16.2,.574,.255,...,19.6,0.7,0.2,1.0,.111,0.2,0.3,0.5,0.3,2019
12,13,Al-Farouq Aminu,PF,28,POR,81,2292,13.2,.568,.472,...,13.7,3.0,2.8,5.8,.121,0.1,0.6,0.7,1.5,2019
13,14,Justin Anderson,SF,25,ATL,48,463,11.2,.516,.490,...,17.2,0.1,0.4,0.4,.043,-2.4,-0.3,-2.7,-0.1,2019
14,15,Kyle Anderson,SF,25,MEM,43,1281,12.8,.569,.123,...,12.6,0.8,1.8,2.7,.100,-1.6,2.4,0.8,0.9,2019
15,16,Ryan Anderson,PF,30,TOT,25,322,4.6,.414,.580,...,12.0,-0.3,0.0,-0.2,-0.035,-4.5,-1.9,-6.4,-0.4,2019
16,16,Ryan Anderson,PF,30,PHO,15,278,4.6,.423,.567,...,12.1,-0.2,0.0,-0.2,-0.039,-4.5,-1.9,-6.3,-0.3,2019
17,16,Ryan Anderson,PF,30,MIA,10,44,4.5,.354,.667,...,11.6,0.0,0.0,0.0,-0.009,-4.6,-1.9,-6.5,0.0,2019
18,17,Ike Anigbogu,C,20,IND,3,6,-6.0,.000,.000,...,29.1,-0.1,0.0,-0.1,-0.480,-14.0,-2.3,-16.2,0.0,2019
19,18,Giannis Antetokounmpo,PF,24,MIL,72,2358,30.9,.644,.163,...,32.3,8.9,5.5,14.4,.292,6.3,4.1,10.4,7.4,2019

This function is to clean out rows for players that played on multiple teams in one season. We only want to keep the TOT row and not the individual team rows.

In [6]:
def single_team(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"]=="TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

regs = regs.groupby(["Player", "Year"]).apply(single_team)
playoffs = playoffs.groupby(["Player", "Year"]).apply(single_team)

In [7]:
regs[regs['Player'] == 'Ryan Anderson']
#removes the extra rows, kept the TOT season stats while showing the team he ended with under 'Tm'

                        Rk         Player Pos Age   Tm   G   MP  PER   TS%  \
Player        Year
Ryan Anderson 2019 15   16  Ryan Anderson  PF  30  MIA  25  322  4.6  .414
              2020 745  12  Ryan Anderson   C  31  HOU   2   14  9.4  .357

                        3PAr  ...  USG%   OWS  DWS    WS   WS/48  OBPM  DBPM  \
Player        Year            ...
Ryan Anderson 2019 15   .580  ...  12.0  -0.3  0.0  -0.2  -0.035  -4.5  -1.9
              2020 745  .714  ...  23.7   0.0  0.0   0.0  -0.037  -3.3   0.5

                         BPM  VORP  Year
Player        Year
Ryan Anderson 2019 15   -6.4  -0.4  2019
              2020 745  -2.8   0.0  2020

[2 rows x 28 columns]

In [8]:
regs.index = regs.index.droplevel()
regs.index = regs.index.droplevel()
playoffs.index = playoffs.index.droplevel()
playoffs.index = playoffs.index.droplevel()

Changed relevant fields to float objects so we can perform analysis.

In [9]:
regs = regs.apply(pd.to_numeric, errors='ignore')
playoffs = playoffs.apply(pd.to_numeric, errors='ignore')

In [10]:
regs.info()
#everything was an object, looks good now

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2725 entries, 3215 to 175
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      2725 non-null   int64
 1   Player  2725 non-null   object
 2   Pos     2725 non-null   object
 3   Age     2725 non-null   int64
 4   Tm      2725 non-null   object
 5   G       2725 non-null   int64
 6   MP      2725 non-null   int64
 7   PER     2725 non-null   float64
 8   TS%     2725 non-null   float64
 9   3PAr    2725 non-null   float64
 10  FTr     2725 non-null   float64
 11  ORB%    2725 non-null   float64
 12  DRB%    2725 non-null   float64
 13  TRB%    2725 non-null   float64
 14  AST%    2725 non-null   float64
 15  STL%    2725 non-null   float64
 16  BLK%    2725 non-null   float64
 17  TOV%    2725 non-null   float64
 18  USG%    2725 non-null   float64
 19  OWS     2725 non-null   float64
 20  DWS     2725 non-null   float64
 21  WS      2725 non-null   float64
 22  WS/48   2725 non-null   float64
 23  OBPM    2725 non-null   float64
 24  DBPM    2725 non-null   float64
 25  BPM     2725 non-null   float64
 26  VORP    2725 non-null   float64
 27  Year    2725 non-null   int64
dtypes: float64(20), int64(5), object(3)
memory usage: 617.4+ KB

In [11]:
regs['SeasonType'] = 'Regular Season'
playoffs['SeasonType'] = 'Playoffs'

In [37]:
regs['MP'].describe()

count    2725.000000
mean     1033.595596
std       782.977636
min         1.000000
25%       288.000000
50%       957.000000
75%      1689.000000
max      3028.000000
Name: MP, dtype: float64

Wanted to further clean the data by making the data set smaller. I removed players who did not play at least 250 minutes in the playoffs. As you can see in the description of the minutes played column above, that should cut a little under 25% of the data. I looked through the players that were about to be cut and I saw that it was fine.

In [12]:
sorted_df = regs.sort_values(by='MP', ascending=True)
    
max_mp = 250
    
# Display the ascending 'Player' and 'MP' columns until MP hits the maximum value
limited_rows = sorted_df[sorted_df['MP'] <= max_mp][['Player', 'MP', 'Year']]

print(limited_rows)

#these guys look safe to remove
#only notable name is Stephen Curry from the season in which he was injured (Warriors missed playoffs)

                  Player   MP  Year
2270         Ahmad Caver    1  2022
572              Zhou Qi    1  2019
170          Tyler Davis    1  2019
2473         Nate Hinton    2  2022
2686         Matt Mooney    2  2022
...                  ...  ...   ...
1939       Justin Patton  247  2021
3477           KZ Okpala  248  2023
1369      Derrick Walton  248  2020
3053  Brandon Boston Jr.  248  2023
1495    Ignas Brazdeikis  249  2021

[640 rows x 3 columns]

In [13]:
regs = regs.drop(limited_rows.index)

In [53]:
regs.info()
#removed about 700 rows

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2085 entries, 3215 to 0
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          2085 non-null   int64
 1   Player      2085 non-null   object
 2   Pos         2085 non-null   object
 3   Age         2085 non-null   int64
 4   Tm          2085 non-null   object
 5   G           2085 non-null   int64
 6   MP          2085 non-null   int64
 7   PER         2085 non-null   float64
 8   TS%         2085 non-null   float64
 9   3PAr        2085 non-null   float64
 10  FTr         2085 non-null   float64
 11  ORB%        2085 non-null   float64
 12  DRB%        2085 non-null   float64
 13  TRB%        2085 non-null   float64
 14  AST%        2085 non-null   float64
 15  STL%        2085 non-null   float64
 16  BLK%        2085 non-null   float64
 17  TOV%        2085 non-null   float64
 18  USG%        2085 non-null   float64
 19  OWS         2085 non-null   float64
 20  DWS         2085 non-null   float64
 21  WS          2085 non-null   float64
 22  WS/48       2085 non-null   float64
 23  OBPM        2085 non-null   float64
 24  DBPM        2085 non-null   float64
 25  BPM         2085 non-null   float64
 26  VORP        2085 non-null   float64
 27  Year        2085 non-null   int64
 28  SeasonType  2085 non-null   object
dtypes: float64(20), int64(5), object(4)
memory usage: 488.7+ KB

In [54]:
playoffs['MP'].describe()

count    1057.000000
mean      192.200568
std       199.284505
min         1.000000
25%        41.000000
50%       133.000000
75%       262.000000
max       983.000000
Name: MP, dtype: float64

Did the same thing with the playoffs data set. The 25th percentile was 41 total minutes, so I set the limit at 25 minutes to cut just under 25% of the data.

In [14]:
sorted_df = playoffs.sort_values(by='MP', ascending=True)
    
max_mp = 35
    
# Display the ascending 'Player' and 'MP' columns until MP hits the maximum value
filtered_rows = sorted_df[sorted_df['MP'] <= max_mp][['Player', 'MP', 'Year']]

print(filtered_rows)

                  Player  MP  Year
451    Ty-Shon Alexander   1  2021
793    Willy Hernangómez   2  2022
89    Isaiah Hartenstein   2  2019
438       Tremont Waters   2  2020
1011       Udonis Haslem   3  2023
...                  ...  ..   ...
665           Mike Scott  34  2021
376      Emmanuel Mudiay  34  2020
608         JaVale McGee  34  2021
164         Semi Ojeleye  34  2019
508       Mamadi Diakite  35  2021

[243 rows x 3 columns]

In [56]:
playoffs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1057 entries, 72 to 1148
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1057 non-null   int64
 1   Player      1057 non-null   object
 2   Pos         1057 non-null   object
 3   Age         1057 non-null   int64
 4   Tm          1057 non-null   object
 5   G           1057 non-null   int64
 6   MP          1057 non-null   int64
 7   PER         1057 non-null   float64
 8   TS%         1057 non-null   float64
 9   3PAr        1057 non-null   float64
 10  FTr         1057 non-null   float64
 11  ORB%        1057 non-null   float64
 12  DRB%        1057 non-null   float64
 13  TRB%        1057 non-null   float64
 14  AST%        1057 non-null   float64
 15  STL%        1057 non-null   float64
 16  BLK%        1057 non-null   float64
 17  TOV%        1057 non-null   float64
 18  USG%        1057 non-null   float64
 19  OWS         1057 non-null   float64
 20  DWS         1057 non-null   float64
 21  WS          1057 non-null   float64
 22  WS/48       1057 non-null   float64
 23  OBPM        1057 non-null   float64
 24  DBPM        1057 non-null   float64
 25  BPM         1057 non-null   float64
 26  VORP        1057 non-null   float64
 27  Year        1057 non-null   int64
 28  SeasonType  1057 non-null   object
dtypes: float64(20), int64(5), object(4)
memory usage: 247.7+ KB

In [15]:
playoffs = playoffs.drop(filtered_rows.index)

In [58]:
playoffs.info()
#removed over 200 rows

<class 'pandas.core.frame.DataFrame'>
Int64Index: 814 entries, 72 to 921
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          814 non-null    int64
 1   Player      814 non-null    object
 2   Pos         814 non-null    object
 3   Age         814 non-null    int64
 4   Tm          814 non-null    object
 5   G           814 non-null    int64
 6   MP          814 non-null    int64
 7   PER         814 non-null    float64
 8   TS%         814 non-null    float64
 9   3PAr        814 non-null    float64
 10  FTr         814 non-null    float64
 11  ORB%        814 non-null    float64
 12  DRB%        814 non-null    float64
 13  TRB%        814 non-null    float64
 14  AST%        814 non-null    float64
 15  STL%        814 non-null    float64
 16  BLK%        814 non-null    float64
 17  TOV%        814 non-null    float64
 18  USG%        814 non-null    float64
 19  OWS         814 non-null    float64
 20  DWS         814 non-null    float64
 21  WS          814 non-null    float64
 22  WS/48       814 non-null    float64
 23  OBPM        814 non-null    float64
 24  DBPM        814 non-null    float64
 25  BPM         814 non-null    float64
 26  VORP        814 non-null    float64
 27  Year        814 non-null    int64
 28  SeasonType  814 non-null    object
dtypes: float64(20), int64(5), object(4)
memory usage: 190.8+ KB

Created a minutes per game column because I felt like this was very important for analysis and it was not present in the scrape from Basketball Reference.

In [20]:
regs['MPG'] = regs['MP'] / regs['G']
playoffs['MPG'] = playoffs['MP'] / playoffs['G']

In [23]:
regs = regs.drop('Rk', axis=1)
playoffs = playoffs.drop('Rk', axis=1)

In [24]:
playoffs.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr', 'FTr',
       'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS',
       'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'Year',
       'SeasonType', 'MPG'],
      dtype='object')

Added a suffix to columns in the playoff dataset to prep for combining rows between regular season and playoffs. It will be merged on player name and year.

In [25]:
columns_to_rename = ['G', 'MP', 'PER', 'TS%', '3PAr', 'FTr',
       'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS',
       'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'MPG']
new_columns = [column + '_p' if column in columns_to_rename else column for column in playoffs.columns]
playoffs = playoffs.rename(columns=dict(zip(playoffs.columns, new_columns)))

playoffs.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G_p', 'MP_p', 'PER_p', 'TS%_p', '3PAr_p',
       'FTr_p', 'ORB%_p', 'DRB%_p', 'TRB%_p', 'AST%_p', 'STL%_p', 'BLK%_p',
       'TOV%_p', 'USG%_p', 'OWS_p', 'DWS_p', 'WS_p', 'WS/48_p', 'OBPM_p',
       'DBPM_p', 'BPM_p', 'VORP_p', 'Year', 'SeasonType', 'MPG_p'],
      dtype='object')

In [26]:
regs.to_csv('C:/Users/kevin/Downloads/regular season stats 2019-2023.csv', index=False)
playoffs.to_csv('C:/Users/kevin/Downloads/playoff stats 2019-2023.csv', index=False)

In [5]:
regs = pd.read_csv("C:/Users/kevin/Downloads/regular season stats 2019-2023.csv")
playoffs = pd.read_csv("C:/Users/kevin/Downloads/playoff stats 2019-2023.csv")

Merging the two data sets in a dataframe called 'combined'

In [6]:
combined = pd.merge(regs, playoffs, on=['Player', 'Year'])

In [7]:
combined.columns

Index(['Player', 'Pos_x', 'Age_x', 'Tm_x', 'G', 'MP', 'PER', 'TS%', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'Year',
       'SeasonType_x', 'MPG', 'Pos_y', 'Age_y', 'Tm_y', 'G_p', 'MP_p', 'PER_p',
       'TS%_p', '3PAr_p', 'FTr_p', 'ORB%_p', 'DRB%_p', 'TRB%_p', 'AST%_p',
       'STL%_p', 'BLK%_p', 'TOV%_p', 'USG%_p', 'OWS_p', 'DWS_p', 'WS_p',
       'WS/48_p', 'OBPM_p', 'DBPM_p', 'BPM_p', 'VORP_p', 'SeasonType_y',
       'MPG_p'],
      dtype='object')

In [8]:
combined = combined.drop(['Pos_y', 'Age_y', 'Tm_y'], axis=1)

In [9]:
combined[['Player', 'Year', 'Pos_x', 'Age_x', 'WS/48', 'WS/48_p']][combined['Player'] == 'LeBron James']

           Player  Year Pos_x  Age_x  WS/48  WS/48_p
488  LeBron James  2020    PG     35  0.204    0.269
489  LeBron James  2021    PG     36  0.179    0.092
490  LeBron James  2023    PF     38  0.138    0.171

Made columns for differences between the playoff number and the regular season number for a few all-in metrics. After some analysis, I settled on WS/48 difference for the rest of this project.

In [10]:
combined['PER_diff'] = combined['PER_p'] - combined['PER']
combined['VORP_diff'] = combined['VORP_p'] - combined['VORP']
combined['WS/48_diff'] = combined['WS/48_p'] - combined['WS/48']

In looking at VORP difference, I found all the best players had the worst VORP differentials. I found this is because VORP is a cumulative stat, so I stopped using this metric in this project.

In [11]:
sorted_df = combined.sort_values(by='VORP_diff', ascending=False)
    
selected_columns = ['Player', 'Year', 'VORP_p', 'VORP', 'VORP_diff']
sorted_df[selected_columns]

#VORP must be a cumulative stat -- all the best players have the worst VORP differentials

              Player  Year  VORP_p  VORP  VORP_diff
191    Dillon Brooks  2021     0.2  -0.9        1.1
37     Austin Rivers  2019     0.0  -1.1        1.1
28   Anfernee Simons  2020     0.1  -0.9        1.0
215  Duncan Robinson  2023     0.5  -0.5        1.0
154  De'Andre Hunter  2022     0.2  -0.8        1.0
..               ...   ...     ...   ...        ...
625      Paul George  2019     0.3   6.6       -6.3
389      Joel Embiid  2022     0.2   6.5       -6.3
583     Nikola Jokić  2021     0.9   8.8       -7.9
336     James Harden  2019     1.1   9.3       -8.2
584     Nikola Jokić  2022     0.6   9.8       -9.2

[797 rows x 5 columns]

In [12]:
sorted_df = combined.sort_values(by='PER_diff', ascending=False)
    
selected_columns = ['Player', 'Year', 'PER_p', 'PER', 'PER_diff']
sorted_df[selected_columns]

                      Player  Year  PER_p   PER  PER_diff
757               Trey Burke  2022   29.6  10.0      19.6
571                     Nenê  2019   30.9  11.9      19.0
663  Rondae Hollis-Jefferson  2019   29.2  12.5      16.7
197         Donovan Mitchell  2020   33.7  18.8      14.9
163         DeMarcus Cousins  2022   32.9  18.2      14.7
..                       ...   ...    ...   ...       ...
248           Furkan Korkmaz  2020   -4.6  12.0     -16.6
730          Thabo Sefolosha  2019   -4.7  12.1     -16.8
374             Jimmy Butler  2021    9.7  26.5     -16.8
502            Malachi Flynn  2022   -5.7  11.7     -17.4
752               Trae Young  2022    5.3  25.4     -20.1

[797 rows x 5 columns]

PER difference seems to work better. There are still a lot of stars at the bottom but that makes sense since they have higher PER to start off with and a poor/short postseason run will lead to a large difference. There were a few stars towards the top of the data though, so this might work better.

In [13]:
sorted_df = combined.sort_values(by='WS/48_diff', ascending=False)
    
selected_columns = ['Player', 'Year', 'WS/48_p', 'WS/48', 'WS/48_diff']
sorted_df[selected_columns]

                      Player  Year  WS/48_p  WS/48  WS/48_diff
571                     Nenê  2019    0.374  0.123       0.251
757               Trey Burke  2022    0.246  0.003       0.243
735              Tim Frazier  2019    0.287  0.084       0.203
663  Rondae Hollis-Jefferson  2019    0.219  0.047       0.172
550              Mike Conley  2020    0.255  0.089       0.166
..                       ...   ...      ...    ...         ...
730          Thabo Sefolosha  2019   -0.186  0.115      -0.301
502            Malachi Flynn  2022   -0.219  0.092      -0.311
374             Jimmy Butler  2021   -0.064  0.255      -0.319
752               Trae Young  2022   -0.139  0.181      -0.320
381               Joe Harris  2023   -0.262  0.083      -0.345

[797 rows x 5 columns]

Using win shares per 48 minutes works as well. However, in both this and the look using PER, some players with very few minutes like Nene and Trey Burke are making their way to the top. I had filtered on total minutes played earlier to remove a chunk of the data set but I might need to do that on minutes per game as well.

In [47]:
combined[combined['Player'] == 'Nenê'][['MP', 'MP_p', 'Year']]

      MP  MP_p  Year
571  546    53  2019

In [48]:
combined['MPG'].describe()

count    797.000000
mean      25.353507
std        6.949235
min        7.947368
25%       19.884058
50%       26.302632
75%       31.287879
max       37.911765
Name: MPG, dtype: float64

In [14]:
def check_players(df, column, max_mp):
    sorted_df = df.sort_values(by=column, ascending=True)

    # Display the ascending 'Player' and 'MP' columns until MP hits the maximum value
    filtered_rows = sorted_df[sorted_df[column] <= max_mp][['Player', column, 'Year']]

    return filtered_rows

In [15]:
check_players(combined, 'MPG', 19)

               Player        MPG  Year
631         Paul Reed   7.947368  2022
57   Boban Marjanović   8.212121  2021
266     Georges Niang   8.745763  2019
56   Boban Marjanović   9.590909  2020
556          Miye Oni   9.611111  2021
..                ...        ...   ...
216     Dwight Howard  18.927536  2020
654   Robert Williams  18.942308  2021
735       Tim Frazier  18.983051  2019
67       Bones Hyland  18.985507  2022
403  Jonathon Simmons  19.000000  2019

[170 rows x 3 columns]

In [53]:
combined['MPG_p'].describe()

count    797.000000
mean      24.897876
std       10.258181
min        3.461538
25%       16.250000
50%       26.200000
75%       34.000000
max       44.000000
Name: MPG_p, dtype: float64

This isn't what I'm looking into but it's interesting to see the variance in minutes per game played is obviously higher in the playoffs, which reflects coaches leaning on their best players for more minutes and playing bench players less.

In [16]:
check_players(combined, 'MPG_p', 19)

                     Player      MPG_p  Year
733  Thanasis Antetokounmpo   3.461538  2021
6             Aaron Nesmith   3.466667  2022
420   Juan Toscano-Anderson   3.500000  2022
735             Tim Frazier   3.636364  2019
757              Trey Burke   3.700000  2022
..                      ...        ...   ...
513         Marco Belinelli  18.714286  2019
531        Matisse Thybulle  18.750000  2020
95            Cameron Payne  19.000000  2021
619        Patrick Beverley  19.000000  2021
314          JaMychal Green  19.000000  2021

[265 rows x 3 columns]

Made a function that allows me to input a minutes per game threshold in the playoffs. If you aren't playing enough to make a difference, no use analyzing the drop off or improvement. I set the MPG limit at 19 for my full data set. Some good bench players here were cut but for the most part these are not high impact players and the PER difference won't matter much.

In [17]:
combined = combined.drop(check_players(combined, 'MPG_p', 19).index)

In [18]:
combined.info()
#whittled down over 200 more players

<class 'pandas.core.frame.DataFrame'>
Int64Index: 532 entries, 0 to 795
Data columns (total 56 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        532 non-null    object
 1   Pos_x         532 non-null    object
 2   Age_x         532 non-null    int64
 3   Tm_x          532 non-null    object
 4   G             532 non-null    int64
 5   MP            532 non-null    int64
 6   PER           532 non-null    float64
 7   TS%           532 non-null    float64
 8   3PAr          532 non-null    float64
 9   FTr           532 non-null    float64
 10  ORB%          532 non-null    float64
 11  DRB%          532 non-null    float64
 12  TRB%          532 non-null    float64
 13  AST%          532 non-null    float64
 14  STL%          532 non-null    float64
 15  BLK%          532 non-null    float64
 16  TOV%          532 non-null    float64
 17  USG%          532 non-null    float64
 18  OWS           532 non-null    float64
 19  DWS           532 non-null    float64
 20  WS            532 non-null    float64
 21  WS/48         532 non-null    float64
 22  OBPM          532 non-null    float64
 23  DBPM          532 non-null    float64
 24  BPM           532 non-null    float64
 25  VORP          532 non-null    float64
 26  Year          532 non-null    int64
 27  SeasonType_x  532 non-null    object
 28  MPG           532 non-null    float64
 29  G_p           532 non-null    int64
 30  MP_p          532 non-null    int64
 31  PER_p         532 non-null    float64
 32  TS%_p         532 non-null    float64
 33  3PAr_p        532 non-null    float64
 34  FTr_p         532 non-null    float64
 35  ORB%_p        532 non-null    float64
 36  DRB%_p        532 non-null    float64
 37  TRB%_p        532 non-null    float64
 38  AST%_p        532 non-null    float64
 39  STL%_p        532 non-null    float64
 40  BLK%_p        532 non-null    float64
 41  TOV%_p        532 non-null    float64
 42  USG%_p        532 non-null    float64
 43  OWS_p         532 non-null    float64
 44  DWS_p         532 non-null    float64
 45  WS_p          532 non-null    float64
 46  WS/48_p       532 non-null    float64
 47  OBPM_p        532 non-null    float64
 48  DBPM_p        532 non-null    float64
 49  BPM_p         532 non-null    float64
 50  VORP_p        532 non-null    float64
 51  SeasonType_y  532 non-null    object
 52  MPG_p         532 non-null    float64
 53  PER_diff      532 non-null    float64
 54  VORP_diff     532 non-null    float64
 55  WS/48_diff    532 non-null    float64
dtypes: float64(45), int64(6), object(5)
memory usage: 236.9+ KB

In [19]:
sorted_df = combined.sort_values(by='PER_diff', ascending=False)
    
selected_columns = ['Player', 'Year', 'PER_p', 'PER', 'PER_diff']
sorted_df[selected_columns]

               Player  Year  PER_p   PER  PER_diff
197  Donovan Mitchell  2020   33.7  18.8      14.9
550       Mike Conley  2020   26.3  14.1      12.2
616   Pat Connaughton  2023   21.3  10.0      11.3
34    Anthony Edwards  2023   27.5  17.4      10.1
91        Cam Reddish  2021   19.2   9.3       9.9
..                ...   ...    ...   ...       ...
436      Kemba Walker  2021    4.3  17.7     -13.4
115      Clint Capela  2022    7.8  21.4     -13.6
587    Nikola Vučević  2019   10.1  25.5     -15.4
374      Jimmy Butler  2021    9.7  26.5     -16.8
752        Trae Young  2022    5.3  25.4     -20.1

[532 rows x 5 columns]

In [20]:
sorted_df = combined.sort_values(by='WS/48_diff', ascending=False)
    
selected_columns = ['Player', 'Year', 'WS/48_p', 'WS/48', 'WS/48_diff']
sorted_df[selected_columns]

               Player  Year  WS/48_p  WS/48  WS/48_diff
550       Mike Conley  2020    0.255  0.089       0.166
197  Donovan Mitchell  2020    0.260  0.110       0.150
91        Cam Reddish  2021    0.173  0.026       0.147
262       George Hill  2019    0.231  0.103       0.128
34    Anthony Edwards  2023    0.190  0.064       0.126
..                ...   ...      ...    ...         ...
422     Julius Randle  2021   -0.109  0.140      -0.249
301         Ish Smith  2019   -0.196  0.064      -0.260
436      Kemba Walker  2021   -0.163  0.115      -0.278
374      Jimmy Butler  2021   -0.064  0.255      -0.319
752        Trae Young  2022   -0.139  0.181      -0.320

[532 rows x 5 columns]

A much better group of players now, with some consistency between both the PER and WS/48 looks.

In [68]:
combined.to_csv('C:/Users/kevin/Downloads/combined 2019-2023.csv', index=False)

In [21]:
check_players(combined, 'MPG_p', 30)

              Player      MPG_p  Year
554       Mike Scott  19.300000  2019
693       Seth Curry  19.333333  2023
411    Jose Alvarado  19.500000  2022
23    Andre Iguodala  19.523810  2020
602  Otto Porter Jr.  19.526316  2022
..               ...        ...   ...
378       Joe Harris  29.800000  2019
515    Marcus Morris  29.846154  2020
1       Aaron Gordon  29.900000  2021
22    Andre Iguodala  29.952381  2019
711     Steven Adams  30.000000  2020

[236 rows x 3 columns]

I then filtered that dataset again to have a playoff MPG limit of 30 minutes. This allows me to only look at starters really, which is where the impact is greatest and noise is lower.

In [22]:
best_players = combined.drop(check_players(combined, 'MPG_p', 30).index)

In [73]:
best_players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 296 entries, 0 to 795
Data columns (total 56 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        296 non-null    object
 1   Pos_x         296 non-null    object
 2   Age_x         296 non-null    int64
 3   Tm_x          296 non-null    object
 4   G             296 non-null    int64
 5   MP            296 non-null    int64
 6   PER           296 non-null    float64
 7   TS%           296 non-null    float64
 8   3PAr          296 non-null    float64
 9   FTr           296 non-null    float64
 10  ORB%          296 non-null    float64
 11  DRB%          296 non-null    float64
 12  TRB%          296 non-null    float64
 13  AST%          296 non-null    float64
 14  STL%          296 non-null    float64
 15  BLK%          296 non-null    float64
 16  TOV%          296 non-null    float64
 17  USG%          296 non-null    float64
 18  OWS           296 non-null    float64
 19  DWS           296 non-null    float64
 20  WS            296 non-null    float64
 21  WS/48         296 non-null    float64
 22  OBPM          296 non-null    float64
 23  DBPM          296 non-null    float64
 24  BPM           296 non-null    float64
 25  VORP          296 non-null    float64
 26  Year          296 non-null    int64
 27  SeasonType_x  296 non-null    object
 28  MPG           296 non-null    float64
 29  G_p           296 non-null    int64
 30  MP_p          296 non-null    int64
 31  PER_p         296 non-null    float64
 32  TS%_p         296 non-null    float64
 33  3PAr_p        296 non-null    float64
 34  FTr_p         296 non-null    float64
 35  ORB%_p        296 non-null    float64
 36  DRB%_p        296 non-null    float64
 37  TRB%_p        296 non-null    float64
 38  AST%_p        296 non-null    float64
 39  STL%_p        296 non-null    float64
 40  BLK%_p        296 non-null    float64
 41  TOV%_p        296 non-null    float64
 42  USG%_p        296 non-null    float64
 43  OWS_p         296 non-null    float64
 44  DWS_p         296 non-null    float64
 45  WS_p          296 non-null    float64
 46  WS/48_p       296 non-null    float64
 47  OBPM_p        296 non-null    float64
 48  DBPM_p        296 non-null    float64
 49  BPM_p         296 non-null    float64
 50  VORP_p        296 non-null    float64
 51  SeasonType_y  296 non-null    object
 52  MPG_p         296 non-null    float64
 53  PER_diff      296 non-null    float64
 54  VORP_diff     296 non-null    float64
 55  WS/48_diff    296 non-null    float64
dtypes: float64(45), int64(6), object(5)
memory usage: 131.8+ KB

I made a second data pull with just the best players because that's what really matters in terms of players raising the level of their play or sinking. 30 minutes per game is a level in the playoffs that only the most trusted players play.

In [23]:
best_players[['Player', 'Year', 'WS/48_p', 'WS/48', 'WS/48_diff', 'MPG_p']].sort_values(by='WS/48_diff', ascending=False)

                    Player  Year  WS/48_p  WS/48  WS/48_diff      MPG_p
550            Mike Conley  2020    0.255  0.089       0.166  33.000000
197       Donovan Mitchell  2020    0.260  0.110       0.150  37.714286
34         Anthony Edwards  2023    0.190  0.064       0.126  39.800000
691             Seth Curry  2021    0.206  0.118       0.088  31.750000
651       Robert Covington  2020    0.169  0.083       0.086  31.583333
..                     ...   ...      ...    ...         ...        ...
276  Giannis Antetokounmpo  2023   -0.026  0.204      -0.230  30.333333
422          Julius Randle  2021   -0.109  0.140      -0.249  36.000000
436           Kemba Walker  2021   -0.163  0.115      -0.278  30.333333
374           Jimmy Butler  2021   -0.064  0.255      -0.319  38.500000
752             Trae Young  2022   -0.139  0.181      -0.320  37.200000

[296 rows x 6 columns]

In [76]:
best_players.to_csv('C:/Users/kevin/Downloads/best players combined 2019-2023.csv', index=False)